CREATE USER HOTEL_ADMIN IDENTIFIED BY "Colita02551!";

GRANT CREATE SESSION TO HOTEL_ADMIN;
GRANT RESOURCE TO HOTEL_ADMIN;

ALTER USER HOTEL_ADMIN QUOTA UNLIMITED ON DATA;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE TO HOTEL_ADMIN;